### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by razmigh** [mouadbroos/COMP353-Repository#1]
A team member can upload a file for an assignment.
Only a team member should be able to manage the file, TA's can only view.

Must keep track of 
- uploader
- file size change
- # of characters, lines (for text files) (ig this can be computed on the spot when needed)
- upload date
- ip address it was uploaded from
- a file checksum
- version number (for allowing rollbacks etc)

**Comment by mouadbouras** [comment]
This issue has been mostly done! 
missing : 
- File size change
- # of characters
- Ip address 
- file checksum

**Comment by mouadbouras** [comment]
Done. 

Missing File size change. 
Closing for now since the change is very unclear in terms of usability and usefulness
